#!/bin/bash

_notes2pdfcomplete() {
	
	local cur prev

	COMPREPLY=()

	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}

	case "$cur" in
		-*)
			COMPREPLY=( $(compgen -W '-h -v -d -e -o -p --help --verbose --debug --execute --output --preview' -- $cur) )
			;;
		*)
			if [[ "$prev" != *".notes" ]] && [[ "$prev" != "--help" ]] && [[ "$prev" != "-h" ]]; then
				COMPREPLY=( $(compgen -f -X '!*.notes' -- $cur) )
			fi
			;;
	esac
}

complete -o filenames -F _notes2pdfcomplete notes2pdf
